### ISSUE TITLE
flox init reads environment.yml (conda) and suggests installation/config

### ISSUE THREAD

**Issue by ghudgins** [flox/flox#1325]
## Original Issue

Conda projects define their Python requirements in a file called `environment.yml`. Our current `flox init` steps are not looking in this file to determine the correct version of Python to add to the manifest.

STR:
```
git clone git@github.com:runew0lf/RuinedFooocus.git
cd RuinedFooocus
ln -s requirements_versions.txt requirements.txt      # see #694 
flox init
```

The contents of `environment.yaml` are:
```yaml
name: ruinedfooocus
channels:
  - defaults
dependencies:
  - python=3.10
  - pip=23.0
  - packaging
```

The resulting `flox list` shows:
```
RuinedFooocus [main●] % flox list
python3: python3 (3.11.8)
RuinedFooocus [main●] %
```

If I then proceed to `flox activate`, the virtual environment is created but `pip install` fails because it's expecting Python 3.10 and Flox has installed Python 3.11.
