### ISSUE TITLE
Possibility to install insecure package ?

### ISSUE THREAD

**Issue by PierreBeucher** [flox/flox#1448]
**Describe the feature:**

I'm trying to install a package marked `insecure` in nixpkgs but it seems there's no option allowing install of (selected) insecure packages.  

```
$ flox install vault
ERROR: package 'vault' failed to evaluate: Package ‘vault-1.14.10’ in /nix/store/4dj2fbzyykakm4x4d0v855r6n5ss9hf9-source/pkgs/tools/security/vault/default.nix:47 is marked as insecure, refusing to evaluate.
 
 
Known issues:
- CVE-2024-2660
 
You can install it anyway by allowing this package, using the
following methods:
 
a) To temporarily allow all insecure packages, you can use an environment
   variable for a single invocation of the nix tools:
 
     $ export NIXPKGS_ALLOW_INSECURE=1
   Note: When using `nix shell`, `nix build`, `nix develop`, etc with a flake,
         then pass `--impure` in order to allow use of environment variables.
b) for `nixos-rebuild` you can add ‘vault-1.14.10’ to
   `nixpkgs.config.permittedInsecurePackages` in the configuration.nix,
   like so:
 
     {
       nixpkgs.config.permittedInsecurePackages = [
         "vault-1.14.10"
       ];
     }
 
c) For `nix-env`, `nix-build`, `nix-shell` or any other Nix command you can add
   ‘vault-1.14.10’ to `permittedInsecurePackages` in
   ~/.config/nixpkgs/config.nix, like so:
 
     {
       permittedInsecurePackages = [
         "vault-1.14.10"
       ];
     }
```

I also tried after `export NIXPKGS_ALLOW_INSECURE=1` to no avail. 

It would be nice to have an option such as:

```
flox install vault --allow-insecure
```

Which could be written in TOML such as

```toml
vault = { pkg-path = "vault", allow-insecure = true }
```

Thanks :)

**Comment by ghudgins** [comment]
as a workaround, you should be able to set that variable to install vault...

<img width="691" alt="image" src="https://github.com/flox/flox/assets/5465514/9930db65-8317-4164-83a8-6bdbf3f60d1c">

**Comment by PierreBeucher** [comment]
Thanks, but as stated (a bit hidden in issue details) it did not seem to be taken into account by flox. We'll try again to make sure we did not miss anything

**Comment by ghudgins** [comment]
yeah, would be interested in understanding why it's not working (as far as a workaround goes)

**Comment by y3lousso** [comment]
- Arch: AMD64
- OS: Win 11 on WSL2 - Ubuntu 22.04

![image](https://github.com/flox/flox/assets/23299699/1fccd9e7-89f7-4c4f-9fd7-c681c36784cd)

**Comment by PierreBeucher** [comment]
Setting `NIXPKGS_ALLOW_INSECURE=1` does not seem to work unfortunately.

```
$ export NIXPKGS_ALLOW_INSECURE=1
$ flox activate                  
❌ ERROR: package 'vault' failed to evaluate: Package ‘vault-1.14.10’ in /nix/store/4dj2fbzyykakm4x4d0v855r6n5ss9hf9-source/pkgs/tools/security/vault/default.nix:47 is marked as insecure, refusing to evaluate.


Known issues:
 - CVE-2024-2660

You can install it anyway by allowing this package, using the
following methods:

a) To temporarily allow all insecure packages, you can use an environment
   variable for a single invocation of the nix tools:

     $ export NIXPKGS_ALLOW_INSECURE=1
     
   Note: When using `nix shell`, `nix build`, `nix develop`, etc with a flake,
         then pass `--impure` in order to allow use of environment variables.
    
b) for `nixos-rebuild` you can add ‘vault-1.14.10’ to
   `nixpkgs.config.permittedInsecurePackages` in the configuration.nix,
   like so:

     {
       nixpkgs.config.permittedInsecurePackages = [
         "vault-1.14.10"
       ];
     }

c) For `nix-env`, `nix-build`, `nix-shell` or any other Nix command you can add
   ‘vault-1.14.10’ to `permittedInsecurePackages` in
   ~/.config/nixpkgs/config.nix, like so:

     {
       permittedInsecurePackages = [
         "vault-1.14.10"
       ];
     }
```

Using `1.0.4-g1696331` with `manifest.toml` on NixOS 23.11

```toml
#
# This is a flox environment manifest.
# Visit flox.dev/docs/concepts/manifest/
# or see flox-edit(1), manifest.toml(1) for more information.
#

# List packages you wish to install in your environment inside
# the `[install]` section.
[install]
go-task.pkg-path = "go-task"
azure-cli.pkg-path = "azure-cli"
bitwarden-cli.pkg-path = "bitwarden-cli"
kubectl.pkg-path = "kubectl"
kubernetes-helm.pkg-path = "kubernetes-helm"
jq.pkg-path = "jq"
k9s.pkg-path = "k9s"
pnpm.pkg-path = "nodePackages.pnpm"
dnsutils.pkg-path = "dnsutils"
dig.pkg-path = "dig"
pulumi.pkg-path = "pulumi"
pulumi-language-nodejs.pkg-path = "pulumiPackages.pulumi-language-nodejs"
pulumi-azure-native.pkg-path = "pulumiPackages.pulumi-azure-native"
vault.pkg-path = "vault"

# Set environment variables in the `[vars]` section.  These variables may not
# reference once another, and are added to the environment without first
# expanding them.  THey are available for use in the `[profile]` and `[hook]`
# scripts.
[vars]
# message = "Howdy"

# Scripts defined in the `[profile]` section are sourced by your shell
# immediately after entering the environment and provide a way to add shell
# aliases to the environment or dynamically compute environment variables.  The
# `profile.common` script is sourced by all shells, so you must write it to be
# compatible with all shells. The `profile.bash` and `profile.zsh` scripts will
# only be sourced by the corresponding shell after sourcing the `profile.common`
# script.
[profile]
common = """
    . .flox/dev-shell-start.sh
"""

# The script defined in `hook.on-activate` is run in a non-interactive Bash
# sub-shell after sourcing the profile scripts. This script inherits all the
# environment variables set in the `[vars]` and `[profile]` sections, but since
# it runs in a sub-shell it can't modify them. The output and exit code of the
# hook script is discarded. The utility of the `hook` script is that it runs in
# a consistent shell environment so you don't have to worry about shell
# compatibility during complicated initialization.
[hook]
# on-activate = """
#     mkdir my_data_dir
# """

# Additional options can be set in the `[options]` section.  Refer to
# manifest.toml(1) for a list of available options.
[options]
allow.unfree=true

# An environment that works on one system is guaranteed to work on the same type
# of system, but other systems may not have the same packages available, etc.
# In order to use the environment on a system you must explicitly add it to the
# `options.systems` list.
systems = ["x86_64-linux"]
```
