### ISSUE TITLE
Fish nested environments don’t work with fish config

### ISSUE THREAD

**Issue by mcolyer** [flox/flox#1577]
**Describe the bug:**

Trying to activate a second environment fails in fish

**Steps to reproduce:**
1. `fish activate` in home
2. `fish activate` in project dir

Result:

```

flox [default] mcolyer@flox ~/apex ❯❯❯ flox activate                                                                                           main
✅ You are now using the environment 'apex'.
To stop using this environment, type 'exit'

Activated flox environment
test: Missing argument at index 3
-ge 2
      ^
~/apex/.flox/run/x86_64-linux.apex/activate.d/fish (line 4): 
if test $_flox_activate_tracelevel -ge 2
   ^
from sourcing file ~/apex/.flox/run/x86_64-linux.apex/activate.d/fish
test: Missing argument at index 3
-ge 2
      ^
~/apex/.flox/run/x86_64-linux.apex/activate.d/fish (line 39): 
if test $_flox_activate_tracelevel -ge 2
   ^
from sourcing file ~/apex/.flox/run/x86_64-linux.apex/activate.d/fish
```

Expected:

That it works

**Screenshots/terminal output (if relevant):**

**flox Version (run `flox --version` if possible):** 1.0.7

**`uname -a` output:** Linux flox 6.8.4-3-pve #1 SMP PREEMPT_DYNAMIC PMX 6.8.4-3 (2024-05-02T11:55Z) x86_64 GNU/Linux

**Comment by ghudgins** [comment]
@mcolyer if you're able, can you include the manifest for the two environments? I'm not able to get this to happen for me on aarch64-linux

<img width="819" alt="image" src="https://github.com/flox/flox/assets/5465514/716c1c0e-02d6-457e-a523-ac09b5051ede">

**Comment by mcolyer** [comment]
They are pretty stock environments:

### default
```toml

[install]
neovim.pkg-path = "neovim"
tig.pkg-path = "tig"
git.pkg-path = "git"
tmux.pkg-path = "tmux"
curl.pkg-path = "curl"
direnv.pkg-path = "direnv"
where.pkg-path = "where"
```

### Nested
```toml

✱
[install]
python3 = { pkg-path = "python3" }

[hook]
on-activate = '''
  # Autogenerated by Flox

  # Setup a Python virtual environment

  export PYTHON_DIR="$FLOX_ENV_CACHE/python"
  if [ ! -d "$PYTHON_DIR" ]; then
    echo "Creating python virtual environment in $PYTHON_DIR"
    python -m venv "$PYTHON_DIR"
  fi

  # Quietly activate venv and install packages in a subshell so
  # that the venv can be freshly activated in the profile section.
  (
    source "$PYTHON_DIR/bin/activate"
    pip install -r "$FLOX_ENV_PROJECT/requirements.txt" --quiet
  )

  # End autogenerated by Flox
'''

[profile]
bash = '''
  # Autogenerated by Flox

  echo "Activating python virtual environment" >&2
  source "$PYTHON_DIR/bin/activate"

  # End autogenerated by Flox
'''
fish = '''
  # Autogenerated by Flox

  echo "Activating python virtual environment" >&2
  source "$PYTHON_DIR/bin/activate.fish"

  # End autogenerated by Flox'''

[options]
systems = ["x86_64-linux"]
```
