### ISSUE TITLE
(install) clearer messages when install downgrades peer packages in a group

### ISSUE THREAD

**Issue by ysndr** [flox/flox#1670]
# Problem

When installing a version constrained package `foo` to a group with an existing package `bar`,
resolution may downgrade or change the precise version (derivation) to one found on a common page with the version constrained `foo`.

# example:

``` toml
version = 1

[install]
dotnet-sdk.pkg-path = "dotnet-sdk"
```

resolves to

```json
{
    "attr_path": "dotnet-sdk",
    "derivation": "/nix/store/bcxaisx8h0g7wj1w3074irr5g8bssxyc-dotnet-sdk-6.0.422.drv",
    ...
}
```

Installing nodejs

```toml
version = 1

[install]
dotnet-sdk.pkg-path = "dotnet-sdk"
nodejs.pkg-path = "nodejs"
nodejs.version = "16.15.0"
```

instead resolves to (v6.0.202 vs v6.0.422)

```diff
{
    "attr_path": "dotnet-sdk",
    "derivation": "/nix/store/a43dsqms211by46p70hvvcyvpxsd2iqy-dotnet-sdk-6.0.202.drv",
    ...
}
```

# AC

Install should check at least for version changes within affected groups and display an informative message.

In the example above:

```
✅ 'nodejs' installed to environment 'dotnet'
   └── `dotnet-sdk` changed (6.0.422 -> 6.0.202)
```
