### ISSUE TITLE
Support for flake based install descriptors in manifest.toml

### ISSUE THREAD

**Issue by ysndr** [flox/flox#1734]
support for flake installables in manifest.toml (already being worked on in https://github.com/flox/flox/pull/1630)

AC

`install` fields may define a catalog target OR a flake installable:

```toml

# descriptor for packages from catalogs (no change)
[install.from-catalog]
pkg-path = "some path"
...

# descriptor for packages from flakes
[install.from-flake]
flake = "github:flox/flox#flox"
```

-----

**open questions**

- attribute name (`flake = ...`, `installable = ...`)
- a single field for the entire url or separate fields for flakeref + attrpath
  - in either case attr-path should follow nix defaults (i.e. no attrpath === `[default]`, `flox` === `[packages.<system>.flox, legacyPackages.<system>.flox, flox]`, `.flox` === `[flox]`)
- how to determine an output for multiple systems outside of default prefixes?
