### ISSUE TITLE
Service command with `entr` doesn't work properly

### ISSUE THREAD

**Issue by nicklewis** [flox/flox#1768]
**Describe the bug:**

Defining a service that uses `entr` to watch and reload a process doesn't seem to work.

**Steps to reproduce:**
1. Add a service to the manifest (in my case it was a flask app started with `python -m [...]`):
```toml
[service.my-cool-service]
command = "git ls-files | entr -r <service command>"
```
2. `flox activate -s`
3. Try to connect to the service

Result:

The service is not running, and there are no logs from process-compose.

Expected:

The `entr` process starts and manages a child process.

**Notes:**

This appears to be a process-compose issue, but if there's a way to make this work, we could at least document the pattern and/or expose the necessary process-compose options.
