### ISSUE TITLE
Removing necessary `priority` field does not cause an error

### ISSUE THREAD

**Issue by zmitchell** [flox/flox#1883]
**Steps to reproduce:**

- Create an environment that requires a priority to solve a conflict:

```toml
version = 1

[install]
python312.pkg-path = "python312"
python313.pkg-path = "python313"
# python313.priority = 6
```

- This should throw an error.
- Now uncomment the `priority` line and the build should succeed.
- Now comment out the `priority` line again and the build should still succeed.

**Expected behavior:**
- A build should not depend on whether a priority was previously set, and should fail in all cases where there is a conflict.
