### ISSUE TITLE
direnv incompatible with services and attach

### ISSUE THREAD

**Issue by dcarley** [flox/flox#2378]
**Describe the bug:**

The activation happens as a one-shot command so a watchdog is started and then immediately torn down:

- https://github.com/flox/flox-direnv/blob/738ae1e821093138e557f7422701aa6405ecb7b9/direnv.rc#L34

An imperative `services start` then starts a new activation and watchdog which immediately tears down the services.

In v1.3.3 (before activation and watchdog changes) services did work but they were left running forever.

**Steps to reproduce:**

1. Clone https://github.com/flox/floxdocs
1. Install `direnv`
1. Activate `direnv allow`
1. Start services imperatively `flox services start`
1. Atttempt to query them with `flox services status`

**Result:**

```
% flox services start
✅ Service 'mkdocs' started.

% flox services status
❌ ERROR: Services not started or quit unexpectedly.
```

**Expected:**

```
% flox services start
✅ Service 'mkdocs' started.

% flox services status
NAME       STATUS            PID
mkdocs     Running         33278
```

**Flox Version (run `flox --version` if possible):**

```
% flox --version 
1.3.4-g4e79475
```

**`uname -a` output:**

```
% uname -a
Darwin mba15.local 23.6.0 Darwin Kernel Version 23.6.0: Thu Sep 12 23:36:06 PDT 2024; root:xnu-10063.141.1.701.1~1/RELEASE_ARM64_T8122 arm64 arm Darwin
```

**Comment by sudermanjr** [comment]
Not sure what the +1 etiquette is here - but I am seeing this issue in version 1.3.8 as well.

**Comment by mkenigs** [comment]
`use_flox` was added to direnv 2.36.0 and has the same issue

**Comment by jasoncorbett** [comment]
I only use direnv to activate flox.  Because of this (and the fact that services don't work), I quickly created something that does what direnv does, but with a subshell through `flox activate`.  It has optional support for -s.  In case this is useful to someone else:
https://github.com/jasoncorbett/flox-auto-activate

**Comment by mkenigs** [comment]
> I only use direnv to activate flox. Because of this (and the fact that services don't work), I quickly created something that does what direnv does, but with a subshell through flox activate. It has optional support for -s. In case this is useful to someone else:
https://github.com/jasoncorbett/flox-auto-activate

Cool we're actually working on adding something like that as part of Flox right now. Once that gets a little further along we'd love it if you could try it out and give us any feedback!

**Comment by richardcooper** [comment]
If we're discussing workarounds, I've been sticking the following in all of my `manifest.toml` files.

```toml
[install]
# Flox currently has a bug which prevents `flox services` from working inside a direnv. See
# https://github.com/flox/flox/issues/2378. As a workaround, we install `process-compose` here.
# `flox services` uses `process-compose` under the hood anyway, so this doesn't add any extra
# dependencies. Installing it just means that the `process-compose` command gets added to our
# $PATH, allowing us to work around the bug by running `process-compose up` in a terminal window
# instead of using `flox services start`.
process-compose.pkg-path = "process-compose"

[vars]
# Path to the service config file used by `process-compose`. This file is automatically
# generated by Flox from the [services] section below. Setting this env-var allows us to run
# `process-compose` without needing to specify the config file path explicitly.
PC_CONFIG_FILES = "${FLOX_ENV}/service-config.yaml"
```

and then running `process-compose up` instead of `flox services start`. The `process-compose` TUI is very nice. Having access to it and more of the `process-compose` features would be pretty nice even if/when this bug gets fixed.
