### ISSUE TITLE
Service specific variables not working

### ISSUE THREAD

**Issue by mkenigs** [flox/flox#2431]
**Describe the bug:**

Service specific variables aren't set

**Steps to reproduce:**
Add to script.sh
```
#!/usr/bin/env bash

echo "FOO: $FOO"
```

`flox edit` and add contents:
```
version = 1

[services]
sleep.command = "insert realpath of script.sh"
sleep.vars.FOO = "bar"
```

```
flox activate -s
flox services logs sleep
```

Result:
`FOO: `

Expected:
`FOO: bar`

**Flox Version (run `flox --version` if possible):**

Dev build post 1.3.4

**Comment by mkenigs** [comment]
Looking at service-config.yaml it looks like we're using `vars` instead of `environment`
```
log_level: debug
log_configuration:
  no_color: true
processes:
  flox_never_exit:
    command: /nix/store/b7j95xd7yccclshfln10k843q2qf20yg-coreutils-9.5/bin/sleep infinity
  sleep:
    command: .../script.sh
    vars:
      FOO: bar
```

**Comment by tomberek** [comment]
It works, in a sense, using the process-compose syntax: https://f1bonacc1.github.io/process-compose/configuration/#local-per-process_1

```toml
version = 1

[services.thing]
command = "echo {{.foo}}; echo done"
vars.foo = "bar"
```
