### ISSUE TITLE
build(manifest): Certificate errors with sandbox=pure

### ISSUE THREAD

**Issue by dcarley** [flox/flox#2461]
**Describe the bug:**
Unable to resolve certificate errors when building something that
- use `sandbox=pure` mode
- fetches dependencies
- on Darwin, where networking is not sandboxed by default

Adding the `cacert` package to the environment does not resolve the issue.

This could be worked around by splitting builds after #TODO and it will never work for Linux but it's indicative of the kinds of problems that users will encounter when moving towards purer builds and we should have some documentation to help them.

**Steps to reproduce:**

`manifest.toml`:
```toml
version = 1

[install]
cargo.pkg-path = "cargo"

[build.tmp]
sandbox = "pure"
command = '''
  cargo build --release
  mkdir -p $out/bin
  cp target/release/tmp $out/bin/tmp
'''
```

`Cargo.toml`:
```toml
[package]
name = "tmp"
version = "0.1.0"
edition = "2021"

[dependencies]
reqwest = { version = "0.11", features = ["blocking"] }
```

`src/main.rs`:
```rust
use reqwest::blocking;
use std::error::Error;

fn main() -> Result<(), Box<dyn Error>> {
    let response = blocking::get("https://canhazip.com/")?
        .text()?;
    println!("Response: {}", response);
    Ok(())
}
```

Run the command:
```sh
flox build
```

**Result:**

```
building '/nix/store/k12jaz8nf8f5bxa8l0xky9lj9wy4vayg-tmp-0.0.0.drv'...
tmp> ---
tmp> Input checksums:
tmp> 455fc11875989ea166224916c2981005  /nix/store/r5wi0mkjhc8146kvhi7ssmcqfiazlqdd-24623475-tmp-src.tar
tmp> f14249f10405c800108eca25694bef30  /nix/store/k6a9n7nncp6piphb0ghx9cxjwpqggf9p-24623475-tmp-build.bash
tmp> ab907a7461ad177752f375fc91aaab73  /nix/store/hahgl7pbmdbrx3v1fmxas0jf7a25vz1x-24623475-tmp-buildCache.tar
tmp> ---
tmp>     Updating crates.io index
tmp> warning: spurious network error (3 tries remaining): [35] SSL connect error (TLS connect error: error:80000002:system library::No such file or directory)
tmp> warning: spurious network error (2 tries remaining): [35] SSL connect error (TLS connect error: error:80000002:system library::No such file or directory)
tmp> warning: spurious network error (1 tries remaining): [35] SSL connect error (TLS connect error: error:80000002:system library::No such file or directory)
tmp> error: failed to get `reqwest` as a dependency of package `tmp v0.1.0 (/private/tmp/nix-build-tmp-0.0.0.drv-0/tmp-0.0.0)`
tmp> Caused by:
tmp>   download of config.json failed
tmp> Caused by:
tmp>   failed to download from `https://index.crates.io/config.json`
tmp> Caused by:
tmp>   [35] SSL connect error (TLS connect error: error:80000002:system library::No such file or directory)
tmp> flox build failed (caching build dir)
ERROR: flox build failed (see /var/folders/8q/spckhr654cv4xrcv0fxsrlvc0000gn/T/tmp.OlgPLLFrR3-build-tmp.log)
make: *** [/nix/store/gagmxfj10wxciph4bgrg608y3yg9xf4c-package-builder-1.0.0/libexec/flox-build.mk:412: result-tmp] Error 1
```

**Expected:**
Dependencies should be downloaded and build succeed.

**Flox Version (run `flox --version` if possible):**
b7673f8ba183d2b8dad9a5f0d050aeebe91395c4

**`uname -a` output:**
```
Darwin mba15.local 23.6.0 Darwin Kernel Version 23.6.0: Thu Sep 12 23:36:06 PDT 2024; root:xnu-10063.141.1.701.1~1/RELEASE_ARM64_T8122 arm64 arm Darwin
```
