### ISSUE TITLE
flox activate -- alias doesn't work for Bash

### ISSUE THREAD

**Issue by dcarley** [flox/flox#2611]
**Describe the bug:**

`flox activate -- alias` doesn't work for Bash where `alias` is defined in a `profile` script.

**Steps to reproduce:**

With this config:
```toml
version = 1

[install]
bash.pkg-path = "bash"
fish.pkg-path = "fish"
tcsh.pkg-path = "tcsh"
zsh.pkg-path = "zsh"

[profile]
common = "alias foo='echo bar'"
tcsh = "alias foo echo bar"

[options]
systems = [
  "aarch64-darwin",
  "aarch64-linux",
  "x86_64-darwin",
  "x86_64-linux",
]
```

Attempt to call the alias with `activate -- command` for each shell:
```sh
for shell in bash fish tcsh zsh; do
  echo -n "$shell:\t"
  FLOX_SHELL="$shell" flox activate -- foo
done
```

**Result:**
```console
bash:	bash: line 1: foo: command not found
fish:	bar
tcsh:	bar
zsh:	bar
```

**Expected:**
```
bash:	bar
fish:	bar
tcsh:	bar
zsh:	bar
```

**Screenshots/terminal output (if relevant):**
This doesn't appear to be a recent regression:
```console
% for version in v1.3.{1..10}; do
  echo "${version}:"
  FLOX_SHELL=bash nix --quiet run --quiet "github:flox/flox/${version}" -- activate -- foo
done
v1.3.1:
bash: line 1: foo: command not found
v1.3.2:
bash: line 1: foo: command not found
v1.3.3:
bash: line 1: foo: command not found
v1.3.4:
bash: line 1: foo: command not found
v1.3.5:
bash: line 1: foo: command not found
v1.3.6:
bash: line 1: foo: command not found
v1.3.7:
bash: line 1: foo: command not found
v1.3.8:
bash: line 1: foo: command not found
v1.3.9:
bash: line 1: foo: command not found
v1.3.10:
bash: line 1: foo: command not found
```

**Flox Version (run `flox --version` if possible):**
v1.3.10 + 249487fc

**`uname -a` output:**
```
Darwin mba15.local 23.6.0 Darwin Kernel Version 23.6.0: Thu Sep 12 23:36:06 PDT 2024; root:xnu-10063.141.1.701.1~1/RELEASE_ARM64_T8122 arm64 arm Darwin
```
