### ISSUE TITLE
Don't generate merge warnings for identical keys

### ISSUE THREAD

**Issue by dcarley** [flox/flox#2846]
**Acceptance criteria**

Don't generate merge warnings when two manifests set a key to the same value, e.g.

Include:
```toml
version = 1

[vars]
foo = "bar"

[options]
systems = [
  "aarch64-darwin",
  "aarch64-linux",
  "x86_64-darwin",
  "x86_64-linux",
]
```

Composer:
```toml
version = 1

[include]
environments = [
  { dir = "../include"}
]

[vars]
foo = "bar"

[options]
systems = [
  "aarch64-darwin",
  "aarch64-linux",
  "x86_64-darwin",
  "x86_64-linux",
]
```

**Why**

It's unnecessarily noisy for users when using `flox edit` or `flox list -c` because the value wasn't overridden with any change and doesn't require any action to be taken. This is especially true for default values that get rendered into the manifest template like `options.systems`. We should only generate a warning if the include was later upgraded/refreshed/zebraed and set a different underlying value.

Internal thread: https://flox-dev.slack.com/archives/C082GP50KG8/p1742922435133409
