### ISSUE TITLE
Flox does not give me the package version specified in `manifest.lock`

### ISSUE THREAD

**Issue by jtmueller** [flox/flox#2856]
**Describe the bug:**

I'm unable to get Flox to upgrade the package `pnpm_10` from version 10.6.3 to version 10.6.5. 

Initially it was telling me that no upgrades were available, so I tried putting it in its own package group, then I tried removing all other packages from the Flox manifest. 

None of that worked, so finally I uninstalled and reinstalled `pnpm_10`. Now the lock file says version 10.6.5, but the binary is still 10.6.3.

After deleting `.flox/cache` and `.flox/run` and re-activating the environment, I still get version 10.6.3.

It tells me no upgrades are available, which makes sense because it also tells me that 10.6.5 is what's currently installed. However, the binary is still version 10.6.3, and it seems that nothing I do can change that.

**Steps to reproduce:**
1. In a project folder, Install `pnpm_10` version 10.6.3
2. Upgrade it to the current version (if you can)

Result:

```bash
❯ which pnpm
/Users/me/dev/my-project/.flox/run/aarch64-darwin.my-project.dev/bin/pnpm
❯ flox list
pnpm_10: pnpm_10 (10.6.5)
❯ pnpm --version
10.6.3
❯ flox upgrade
No upgrades available for packages in 'my-project'.
❯ exit
❯ rm -rf .flox/cache
❯ rm -rf .flox/run
❯ rm -rf .flox/log
❯ flox list
pnpm_10: pnpm_10 (10.6.5)
❯ flox activate
✅ You are now using the environment 'my-project'.
To stop using this environment, type 'exit'
❯ which pnpm
/Users/me/dev/my-project/.flox/run/aarch64-darwin.my-project.dev/bin/pnpm
❯ pnpm --version
10.6.3
```

Expected:

A package manager should provide a way to upgrade a package.

**Screenshots/terminal output (if relevant):**

**Flox Version (run `flox --version` if possible):** 
1.3.16

**`uname -a` output:**

Darwin My-MacBook-Pro-2.local 24.3.0 Darwin Kernel Version 24.3.0: Thu Jan  2 20:24:24 PST 2025; root:xnu-11215.81.4~3/RELEASE_ARM64_T6030 arm64

**Comment by mkenigs** [comment]
I'm not reproducing with a `flox install pnpm_10@10.6.3`, but there may be some state in your lockfile. Do you have a start to finish reproducer, or is it only happening because pnpm_10 latest was previously 10.6.3? If there isn't some other reproducer, could you send your `manifest.toml` and `manifest.lock` files if they don't have anything you want to keep private?

This works as I'd expect:
```
/tmp  > flox init
✨ Created environment 'tmp' (aarch64-darwin)

Next:
  $ flox search <package>    <- Search for a package
  $ flox install <package>   <- Install a package into an environment
  $ flox activate            <- Enter the environment
  $ flox edit                <- Add environment variables and shell hooks

/tmp  > flox install pnpm_10@10.6.3
✅ 'pnpm_10' installed to environment 'tmp'
/tmp  > flox activate
✅ You are now using the environment 'tmp'.
To stop using this environment, type 'exit'

flox [tmp] /tmp  > pnpm --version
10.6.3
flox [tmp] /tmp  > flox edit
✅ Environment successfully updated.
flox [tmp] /tmp  > pnpm --version
10.6.5
```

**Comment by jtmueller** [comment]
@mkenigs - Thanks for looking into this. I see the same thing as you in a standalone isolated environment. Although I didn't use `flox edit` to remove the version constraint because I've been refusing to learn vi or vim since the 90's and that's not about to change now. As a result, I had to exit the flox shell, use a different editor to remove the version constraint, and then re-activate flox. But in that situation, it did update to 10.6.5.

However, if I do the exact same thing in my project (exit, edit the manifest to remove the version constraint, re-activate) the lock file remains on pnpm 10.6.3.

If I uninstall the `pnpm` package this project is using and instead install `pnpm_10` without a version constraint, I'm still on 10.6.3 in manifest.lock, despite switching package names.

If I then uninstall `pnpm_10` and install `pnpm_10@10.6.5` and then `flox activate` the lock file is updated to refer to 10.6.5, but **my local binary remains at 10.6.3** which is kind of the most disturbing thing of all.

It's probably worth mentioning that I have a "default" flox environment that is automatically activated in my `.zprofile` that has pnpm version 10.6.3 in it, but that version is not the binary being run in this case - it's the binary linked into the local `.flox` directory according to `which pnpm`.

```
❯ flox envs --active
✨ Active environments:
  nav-portal         /Users/me/dev/nav-portal
  default            /Users/me
```

The manifest and lock files aren't especially sensitive, here they are:

manifest.toml:
```toml
## Flox Environment Manifest -----------------------------------------
##
##   _Everything_ you need to know about the _manifest_ is here:
##
##               https://flox.dev/docs/concepts/manifest
##
## -------------------------------------------------------------------
# Flox manifest version managed by Flox CLI
version = 1


## Install Packages --------------------------------------------------
##  $ flox install gum  <- puts a package in [install] section below
##  $ flox search gum   <- search for a package
##  $ flox show gum     <- show all versions of a package
## -------------------------------------------------------------------
[install]
postgresql_16.pkg-path = "postgresql_16"
gum.pkg-path = "gum"
nodejs.pkg-path = "nodejs"
nodejs.version = "22.14.0"
pnpm.pkg-path = "pnpm"
pnpm.version = "10.6.3"

## Environment Variables ---------------------------------------------
##  ... available for use in the activated environment
##      as well as [hook], [profile] scripts and [services] below.
## -------------------------------------------------------------------
[vars]
PGHOSTADDR = "127.0.0.1"
PGPORT = "6432"
PGUSER = "postgres"
PGPASS = "postgres"
PGDATABASE = "nav-portal"


## Activation Hook ---------------------------------------------------
##  ... run by _bash_ shell when you run 'flox activate'.
## -------------------------------------------------------------------
[hook]
on-activate = '''
  # Install nodejs dependencies
  pnpm install

  # Setup PostgreSQL
export PGDIR="$FLOX_ENV_CACHE/postgres"
export PGDATA=$PGDIR/data
export PGHOST=$PGDIR/run
export PGCONFIGFILE="$PGDIR/postgresql.conf"
export LOG_PATH=$PGHOST/LOG
export SESSION_SECRET="$USER-session-secret"
export DATABASE_URL="postgres://$PGUSER:$PGPASS@$PGHOSTADDR:$PGPORT/$PGDATABASE"

if [[ ! -d "$PGHOST" ]]; then
  mkdir -p "$PGHOST"
fi

if [[ ! -d "$PGDATA" ]]; then
  mkdir -p "$PGDATA"
  pg_initdb() {
    initdb "$PGDATA" \
      --locale=C \
      --encoding=UTF8 \
      -A md5 \
      --auth=trust \
      --username $PGUSER \
      --pwfile=<(echo $PGPASS)
  }
  export -f pg_initdb  # This is needed for gum to be able to call function
  if [[ "$FLOX_ENVS_TESTING" == "1" ]]; then
    pg_initdb
  else
    gum spin --spinner dot --title "Running initdb in $PGDATA" -- bash -c pg_initdb
  fi
  echo "✅ Initialize PostgreSQL ($PGDATA)"

fi


#
if [[ ! -f "$PGCONFIGFILE" ]]; then
  tee -a $PGCONFIGFILE > /dev/null << EOF
listen_addresses = '$PGHOSTADDR';
port = '$PGPORT';
unix_socket_directories = '$PGHOST';
unix_socket_permissions = '0700';
EOF
  echo "✅ Configure PostgreSQL ($PGCONFIGFILE)"


  pg_ctl -D "$PGDATA" -w start -o "-c unix_socket_directories=$PGHOST -c listen_addresses=$PGHOSTADDR -p $PGPORT" > /dev/null
  if psql -lqt | cut -d \| -f 1 | grep -qw $PGDATABASE; then
    echo "✅ Database '$PGDATABASE' already exists"
  else
    createdb
    echo "✅ Database '$PGDATABASE' created"
  fi
  pg_ctl -D "$PGDATA" -m fast -w stop > /dev/null
fi
'''


## Profile script ----------------------------------------------------
## ... sourced by _your shell_ when you run 'flox activate'.
## -------------------------------------------------------------------
[profile]
# common = '''
#   gum style \
#   --foreground 212 --border-foreground 212 --border double \
#   --align center --width 50 --margin "1 2" --padding "2 4" \
#     $INTRO_MESSAGE
# '''
## Shell specific profiles go here:
# bash = ...
# zsh  = ...
# fish = ...


## Services ----------------------------------------------------------
##  $ flox services start             <- Starts all services
##  $ flox services status            <- Status of running services
##  $ flox activate --start-services  <- Activates & starts all
## -------------------------------------------------------------------
[services]
postgres.command = "postgres"


## Other Environment Options -----------------------------------------
[options]
# Systems that environment is compatible with
systems = ["aarch64-darwin", "aarch64-linux", "x86_64-darwin", "x86_64-linux"]
# Uncomment to disable CUDA detection.
# cuda-detection = false
```

manifest.lock:
```json
{
  "lockfile-version": 1,
  "manifest": {
    "version": 1,
    "install": {
      "gum": {
        "pkg-path": "gum"
      },
      "nodejs": {
        "pkg-path": "nodejs",
        "version": "22.14.0"
      },
      "pnpm": {
        "pkg-path": "pnpm",
        "version": "10.6.3"
      },
      "postgresql_16": {
        "pkg-path": "postgresql_16"
      }
    },
    "vars": {
      "PGDATABASE": "nav-portal",
      "PGHOSTADDR": "127.0.0.1",
      "PGPASS": "postgres",
      "PGPORT": "6432",
      "PGUSER": "postgres"
    },
    "hook": {
      "on-activate": "  # Install nodejs dependencies\n  pnpm install\n\n  # Setup PostgreSQL\nexport PGDIR=\"$FLOX_ENV_CACHE/postgres\"\nexport PGDATA=$PGDIR/data\nexport PGHOST=$PGDIR/run\nexport PGCONFIGFILE=\"$PGDIR/postgresql.conf\"\nexport LOG_PATH=$PGHOST/LOG\nexport SESSION_SECRET=\"$USER-session-secret\"\nexport DATABASE_URL=\"postgres://$PGUSER:$PGPASS@$PGHOSTADDR:$PGPORT/$PGDATABASE\"\n\nif [[ ! -d \"$PGHOST\" ]]; then\n  mkdir -p \"$PGHOST\"\nfi\n\nif [[ ! -d \"$PGDATA\" ]]; then\n  mkdir -p \"$PGDATA\"\n  pg_initdb() {\n    initdb \"$PGDATA\" \\\n      --locale=C \\\n      --encoding=UTF8 \\\n      -A md5 \\\n      --auth=trust \\\n      --username $PGUSER \\\n      --pwfile=<(echo $PGPASS)\n  }\n  export -f pg_initdb  # This is needed for gum to be able to call function\n  if [[ \"$FLOX_ENVS_TESTING\" == \"1\" ]]; then\n    pg_initdb\n  else\n    gum spin --spinner dot --title \"Running initdb in $PGDATA\" -- bash -c pg_initdb\n  fi\n  echo \"✅ Initialize PostgreSQL ($PGDATA)\"\n\nfi\n\n\n#\nif [[ ! -f \"$PGCONFIGFILE\" ]]; then\n  tee -a $PGCONFIGFILE > /dev/null << EOF\nlisten_addresses = '$PGHOSTADDR';\nport = '$PGPORT';\nunix_socket_directories = '$PGHOST';\nunix_socket_permissions = '0700';\nEOF\n  echo \"✅ Configure PostgreSQL ($PGCONFIGFILE)\"\n\n\n  pg_ctl -D \"$PGDATA\" -w start -o \"-c unix_socket_directories=$PGHOST -c listen_addresses=$PGHOSTADDR -p $PGPORT\" > /dev/null\n  if psql -lqt | cut -d \\| -f 1 | grep -qw $PGDATABASE; then\n    echo \"✅ Database '$PGDATABASE' already exists\"\n  else\n    createdb\n    echo \"✅ Database '$PGDATABASE' created\"\n  fi\n  pg_ctl -D \"$PGDATA\" -m fast -w stop > /dev/null\nfi\n"
    },
    "profile": {},
    "options": {
      "systems": [
        "aarch64-darwin",
        "aarch64-linux",
        "x86_64-darwin",
        "x86_64-linux"
      ],
      "allow": {
        "licenses": []
      },
      "semver": {}
    },
    "services": {
      "postgres": {
        "command": "postgres"
      }
    }
  },
  "packages": [
    {
      "attr_path": "gum",
      "broken": false,
      "derivation": "/nix/store/rs3gh60pcnvw9gfmgflinhqmyl8klwp5-gum-0.16.0.drv",
      "description": "Tasty Bubble Gum for your shell",
      "install_id": "gum",
      "license": "MIT",
      "locked_url": "https://github.com/flox/nixpkgs?rev=b6eaf97c6960d97350c584de1b6dcff03c9daf42",
      "name": "gum-0.16.0",
      "pname": "gum",
      "rev": "b6eaf97c6960d97350c584de1b6dcff03c9daf42",
      "rev_count": 769969,
      "rev_date": "2025-03-18T09:06:34Z",
      "scrape_date": "2025-03-20T01:09:45.087690Z",
      "stabilities": [
        "unstable"
      ],
      "unfree": false,
      "version": "0.16.0",
      "outputs_to_install": [
        "out"
      ],
      "outputs": {
        "out": "/nix/store/kwkfj9ifihlfzv7damvf0x42w1l904ld-gum-0.16.0"
      },
      "system": "aarch64-darwin",
      "group": "toplevel",
      "priority": 5
    },
    {
      "attr_path": "gum",
      "broken": false,
      "derivation": "/nix/store/rfdkq3mnxjbn28fr3w9a8wlb6id80lpy-gum-0.16.0.drv",
      "description": "Tasty Bubble Gum for your shell",
      "install_id": "gum",
      "license": "MIT",
      "locked_url": "https://github.com/flox/nixpkgs?rev=b6eaf97c6960d97350c584de1b6dcff03c9daf42",
      "name": "gum-0.16.0",
      "pname": "gum",
      "rev": "b6eaf97c6960d97350c584de1b6dcff03c9daf42",
      "rev_count": 769969,
      "rev_date": "2025-03-18T09:06:34Z",
      "scrape_date": "2025-03-20T01:28:05.764040Z",
      "stabilities": [
        "unstable"
      ],
      "unfree": false,
      "version": "0.16.0",
      "outputs_to_install": [
        "out"
      ],
      "outputs": {
        "out": "/nix/store/fflgnfjyizrfp3kb9kg1rb13zh8iqgpa-gum-0.16.0"
      },
      "system": "aarch64-linux",
      "group": "toplevel",
      "priority": 5
    },
    {
      "attr_path": "gum",
      "broken": false,
      "derivation": "/nix/store/lqp6sr5qq6zd802sfxrkb9m9jd63ymrz-gum-0.16.0.drv",
      "description": "Tasty Bubble Gum for your shell",
      "install_id": "gum",
      "license": "MIT",
      "locked_url": "https://github.com/flox/nixpkgs?rev=b6eaf97c6960d97350c584de1b6dcff03c9daf42",
      "name": "gum-0.16.0",
      "pname": "gum",
      "rev": "b6eaf97c6960d97350c584de1b6dcff03c9daf42",
      "rev_count": 769969,
      "rev_date": "2025-03-18T09:06:34Z",
      "scrape_date": "2025-03-20T01:44:38.963224Z",
      "stabilities": [
        "unstable"
      ],
      "unfree": false,
      "version": "0.16.0",
      "outputs_to_install": [
        "out"
      ],
      "outputs": {
        "out": "/nix/store/854g6bmylzpaz7s1xdccfq9x2xkx6fcc-gum-0.16.0"
      },
      "system": "x86_64-darwin",
      "group": "toplevel",
      "priority": 5
    },
    {
      "attr_path": "gum",
      "broken": false,
      "derivation": "/nix/store/24a1pj733gimjh92rd6biprlpql2fdaa-gum-0.16.0.drv",
      "description": "Tasty Bubble Gum for your shell",
      "install_id": "gum",
      "license": "MIT",
      "locked_url": "https://github.com/flox/nixpkgs?rev=b6eaf97c6960d97350c584de1b6dcff03c9daf42",
      "name": "gum-0.16.0",
      "pname": "gum",
      "rev": "b6eaf97c6960d97350c584de1b6dcff03c9daf42",
      "rev_count": 769969,
      "rev_date": "2025-03-18T09:06:34Z",
      "scrape_date": "2025-03-20T02:04:11.534944Z",
      "stabilities": [
        "unstable"
      ],
      "unfree": false,
      "version": "0.16.0",
      "outputs_to_install": [
        "out"
      ],
      "outputs": {
        "out": "/nix/store/hn1dl52063dlljmzjlx0cw1f59yk5r2n-gum-0.16.0"
      },
      "system": "x86_64-linux",
      "group": "toplevel",
      "priority": 5
    },
    {
      "attr_path": "nodejs",
      "broken": false,
      "derivation": "/nix/store/0vf1qjh3y9f9f9z6w2rhj69xj3sjlcdq-nodejs-22.14.0.drv",
      "description": "Event-driven I/O framework for the V8 JavaScript engine",
      "install_id": "nodejs",
      "license": "MIT",
      "locked_url": "https://github.com/flox/nixpkgs?rev=b6eaf97c6960d97350c584de1b6dcff03c9daf42",
      "name": "nodejs-22.14.0",
      "pname": "nodejs",
      "rev": "b6eaf97c6960d97350c584de1b6dcff03c9daf42",
      "rev_count": 769969,
      "rev_date": "2025-03-18T09:06:34Z",
      "scrape_date": "2025-03-20T01:09:47.006661Z",
      "stabilities": [
        "unstable"
      ],
      "unfree": false,
      "version": "22.14.0",
      "outputs_to_install": [
        "out"
      ],
      "outputs": {
        "libv8": "/nix/store/q6xnd2kar3sh0jnwic7z2k0fm3450xrs-nodejs-22.14.0-libv8",
        "out": "/nix/store/gxr9abzyqmva25p3k142qs1djj9q5fqw-nodejs-22.14.0"
      },
      "system": "aarch64-darwin",
      "group": "toplevel",
      "priority": 5
    },
    {
      "attr_path": "nodejs",
      "broken": false,
      "derivation": "/nix/store/mv2wz78naj8v3vxzd394zjbczr49a3nq-nodejs-22.14.0.drv",
      "description": "Event-driven I/O framework for the V8 JavaScript engine",
      "install_id": "nodejs",
      "license": "MIT",
      "locked_url": "https://github.com/flox/nixpkgs?rev=b6eaf97c6960d97350c584de1b6dcff03c9daf42",
      "name": "nodejs-22.14.0",
      "pname": "nodejs",
      "rev": "b6eaf97c6960d97350c584de1b6dcff03c9daf42",
      "rev_count": 769969,
      "rev_date": "2025-03-18T09:06:34Z",
      "scrape_date": "2025-03-20T01:28:14.118115Z",
      "stabilities": [
        "unstable"
      ],
      "unfree": false,
      "version": "22.14.0",
      "outputs_to_install": [
        "out"
      ],
      "outputs": {
        "libv8": "/nix/store/5qv5cl1s9hjhyjhd4nmgndf1ccf3mc4r-nodejs-22.14.0-libv8",
        "out": "/nix/store/5baih13vgavgia3889wsvh4n4z0mkawd-nodejs-22.14.0"
      },
      "system": "aarch64-linux",
      "group": "toplevel",
      "priority": 5
    },
    {
      "attr_path": "nodejs",
      "broken": false,
      "derivation": "/nix/store/4cqnziwc9xm2cs9wa7f6hqbfk1p16pg3-nodejs-22.14.0.drv",
      "description": "Event-driven I/O framework for the V8 JavaScript engine",
      "install_id": "nodejs",
      "license": "MIT",
      "locked_url": "https://github.com/flox/nixpkgs?rev=b6eaf97c6960d97350c584de1b6dcff03c9daf42",
      "name": "nodejs-22.14.0",
      "pname": "nodejs",
      "rev": "b6eaf97c6960d97350c584de1b6dcff03c9daf42",
      "rev_count": 769969,
      "rev_date": "2025-03-18T09:06:34Z",
      "scrape_date": "2025-03-20T01:44:40.929723Z",
      "stabilities": [
        "unstable"
      ],
      "unfree": false,
      "version": "22.14.0",
      "outputs_to_install": [
        "out"
      ],
      "outputs": {
        "libv8": "/nix/store/jg0m7pq2hvqrkm1vx22sghqvc9vnn35h-nodejs-22.14.0-libv8",
        "out": "/nix/store/8b56xv3fa7v0w0kpr2yvkxq6cb2kknd0-nodejs-22.14.0"
      },
      "system": "x86_64-darwin",
      "group": "toplevel",
      "priority": 5
    },
    {
      "attr_path": "nodejs",
      "broken": false,
      "derivation": "/nix/store/355wccz7k0y4wz9y0fvp063xrfq3n1nc-nodejs-22.14.0.drv",
      "description": "Event-driven I/O framework for the V8 JavaScript engine",
      "install_id": "nodejs",
      "license": "MIT",
      "locked_url": "https://github.com/flox/nixpkgs?rev=b6eaf97c6960d97350c584de1b6dcff03c9daf42",
      "name": "nodejs-22.14.0",
      "pname": "nodejs",
      "rev": "b6eaf97c6960d97350c584de1b6dcff03c9daf42",
      "rev_count": 769969,
      "rev_date": "2025-03-18T09:06:34Z",
      "scrape_date": "2025-03-20T02:04:21.515396Z",
      "stabilities": [
        "unstable"
      ],
      "unfree": false,
      "version": "22.14.0",
      "outputs_to_install": [
        "out"
      ],
      "outputs": {
        "libv8": "/nix/store/hs3x57x6gw75sgwa081d3ir63rz7phmb-nodejs-22.14.0-libv8",
        "out": "/nix/store/87hsv7pc321h80j7223209nxc8vmabqb-nodejs-22.14.0"
      },
      "system": "x86_64-linux",
      "group": "toplevel",
      "priority": 5
    },
    {
      "attr_path": "pnpm",
      "broken": false,
      "derivation": "/nix/store/3i7wk27bzfpcnplxi5j59mqza2sp375n-pnpm-10.6.3.drv",
      "description": "Fast, disk space efficient package manager for JavaScript",
      "install_id": "pnpm",
      "license": "MIT",
      "locked_url": "https://github.com/flox/nixpkgs?rev=b6eaf97c6960d97350c584de1b6dcff03c9daf42",
      "name": "pnpm-10.6.3",
      "pname": "pnpm",
      "rev": "b6eaf97c6960d97350c584de1b6dcff03c9daf42",
      "rev_count": 769969,
      "rev_date": "2025-03-18T09:06:34Z",
      "scrape_date": "2025-03-20T01:09:51.757221Z",
      "stabilities": [
        "unstable"
      ],
      "unfree": false,
      "version": "10.6.3",
      "outputs_to_install": [
        "out"
      ],
      "outputs": {
        "out": "/nix/store/l0y8lg6hf8d3dcqlblf6azg3pgrmxk3h-pnpm-10.6.3"
      },
      "system": "aarch64-darwin",
      "group": "toplevel",
      "priority": 5
    },
    {
      "attr_path": "pnpm",
      "broken": false,
      "derivation": "/nix/store/90yhrdz8yy11r326n29bzzr2qpzcbaac-pnpm-10.6.3.drv",
      "description": "Fast, disk space efficient package manager for JavaScript",
      "install_id": "pnpm",
      "license": "MIT",
      "locked_url": "https://github.com/flox/nixpkgs?rev=b6eaf97c6960d97350c584de1b6dcff03c9daf42",
      "name": "pnpm-10.6.3",
      "pname": "pnpm",
      "rev": "b6eaf97c6960d97350c584de1b6dcff03c9daf42",
      "rev_count": 769969,
      "rev_date": "2025-03-18T09:06:34Z",
      "scrape_date": "2025-03-20T01:28:23.426067Z",
      "stabilities": [
        "unstable"
      ],
      "unfree": false,
      "version": "10.6.3",
      "outputs_to_install": [
        "out"
      ],
      "outputs": {
        "out": "/nix/store/hz3gb73iijipqvf8ghid066pdhg1gbx5-pnpm-10.6.3"
      },
      "system": "aarch64-linux",
      "group": "toplevel",
      "priority": 5
    },
    {
      "attr_path": "pnpm",
      "broken": false,
      "derivation": "/nix/store/2igrmx6bx6yqhnnvyrh547i3xlsshfdl-pnpm-10.6.3.drv",
      "description": "Fast, disk space efficient package manager for JavaScript",
      "install_id": "pnpm",
      "license": "MIT",
      "locked_url": "https://github.com/flox/nixpkgs?rev=b6eaf97c6960d97350c584de1b6dcff03c9daf42",
      "name": "pnpm-10.6.3",
      "pname": "pnpm",
      "rev": "b6eaf97c6960d97350c584de1b6dcff03c9daf42",
      "rev_count": 769969,
      "rev_date": "2025-03-18T09:06:34Z",
      "scrape_date": "2025-03-20T01:44:45.762865Z",
      "stabilities": [
        "unstable"
      ],
      "unfree": false,
      "version": "10.6.3",
      "outputs_to_install": [
        "out"
      ],
      "outputs": {
        "out": "/nix/store/73n49s5icjskippv48pn4swgr1qsxllv-pnpm-10.6.3"
      },
      "system": "x86_64-darwin",
      "group": "toplevel",
      "priority": 5
    },
    {
      "attr_path": "pnpm",
      "broken": false,
      "derivation": "/nix/store/l3c9my6q27k8169jlax7cw44yr97j97b-pnpm-10.6.3.drv",
      "description": "Fast, disk space efficient package manager for JavaScript",
      "install_id": "pnpm",
      "license": "MIT",
      "locked_url": "https://github.com/flox/nixpkgs?rev=b6eaf97c6960d97350c584de1b6dcff03c9daf42",
      "name": "pnpm-10.6.3",
      "pname": "pnpm",
      "rev": "b6eaf97c6960d97350c584de1b6dcff03c9daf42",
      "rev_count": 769969,
      "rev_date": "2025-03-18T09:06:34Z",
      "scrape_date": "2025-03-20T02:04:31.620460Z",
      "stabilities": [
        "unstable"
      ],
      "unfree": false,
      "version": "10.6.3",
      "outputs_to_install": [
        "out"
      ],
      "outputs": {
        "out": "/nix/store/nrx9a9adgnhspm5lqgcyl9vycsyqwfyh-pnpm-10.6.3"
      },
      "system": "x86_64-linux",
      "group": "toplevel",
      "priority": 5
    },
    {
      "attr_path": "postgresql_16",
      "broken": false,
      "derivation": "/nix/store/3czq1a67pbpkkmh969b6mwjbl6fzal7z-postgresql-16.8.drv",
      "description": "Powerful, open source object-relational database system",
      "install_id": "postgresql_16",
      "license": "PostgreSQL",
      "locked_url": "https://github.com/flox/nixpkgs?rev=b6eaf97c6960d97350c584de1b6dcff03c9daf42",
      "name": "postgresql-16.8",
      "pname": "postgresql_16",
      "rev": "b6eaf97c6960d97350c584de1b6dcff03c9daf42",
      "rev_count": 769969,
      "rev_date": "2025-03-18T09:06:34Z",
      "scrape_date": "2025-03-20T01:09:52.292396Z",
      "stabilities": [
        "unstable"
      ],
      "unfree": false,
      "version": "16.8",
      "outputs_to_install": [
        "man",
        "out"
      ],
      "outputs": {
        "dev": "/nix/store/5fgsl08cwh6v4wsfs7s9s9cgm29h6wj2-postgresql-16.8-dev",
        "doc": "/nix/store/3k0kpf066y3h9fl2375p35mqhqxjp3vm-postgresql-16.8-doc",
        "lib": "/nix/store/k0mvaafry5yyfklxhvzxxzf1in869ms6-postgresql-16.8-lib",
        "man": "/nix/store/pp3330kg3dfji9sifw7xb08xpc2ksj2a-postgresql-16.8-man",
        "out": "/nix/store/yvd4n7lf2a39i3bq82id6hc1vcw8djms-postgresql-16.8"
      },
      "system": "aarch64-darwin",
      "group": "toplevel",
      "priority": 5
    },
    {
      "attr_path": "postgresql_16",
      "broken": false,
      "derivation": "/nix/store/k9qksg2rd4x16h0cl9hzzpx60v99hx78-postgresql-16.8.drv",
      "description": "Powerful, open source object-relational database system",
      "install_id": "postgresql_16",
      "license": "PostgreSQL",
      "locked_url": "https://github.com/flox/nixpkgs?rev=b6eaf97c6960d97350c584de1b6dcff03c9daf42",
      "name": "postgresql-16.8",
      "pname": "postgresql_16",
      "rev": "b6eaf97c6960d97350c584de1b6dcff03c9daf42",
      "rev_count": 769969,
      "rev_date": "2025-03-18T09:06:34Z",
      "scrape_date": "2025-03-20T01:28:24.375741Z",
      "stabilities": [
        "unstable"
      ],
      "unfree": false,
      "version": "16.8",
      "outputs_to_install": [
        "man",
        "out"
      ],
      "outputs": {
        "debug": "/nix/store/8rrb5s40p1iq38zjn0vyxjlm3jcgqk9h-postgresql-16.8-debug",
        "dev": "/nix/store/cwn3fvmlw4578d90wi5nr3f8bsvlsx5i-postgresql-16.8-dev",
        "doc": "/nix/store/ba04q2gq0m0yxj03zi59rihchj4dyxi4-postgresql-16.8-doc",
        "lib": "/nix/store/6cvpddnrz14p7ipq8xdkclrxv7r4zx4x-postgresql-16.8-lib",
        "man": "/nix/store/i89q7sdxla3w8a22yjpw48g80irs3fny-postgresql-16.8-man",
        "out": "/nix/store/p6dpfjd241njw4005l3j6sb8j0c3qvs3-postgresql-16.8"
      },
      "system": "aarch64-linux",
      "group": "toplevel",
      "priority": 5
    },
    {
      "attr_path": "postgresql_16",
      "broken": false,
      "derivation": "/nix/store/pnkch7y9vmp63z0h0qm2y152y14c9s5f-postgresql-16.8.drv",
      "description": "Powerful, open source object-relational database system",
      "install_id": "postgresql_16",
      "license": "PostgreSQL",
      "locked_url": "https://github.com/flox/nixpkgs?rev=b6eaf97c6960d97350c584de1b6dcff03c9daf42",
      "name": "postgresql-16.8",
      "pname": "postgresql_16",
      "rev": "b6eaf97c6960d97350c584de1b6dcff03c9daf42",
      "rev_count": 769969,
      "rev_date": "2025-03-18T09:06:34Z",
      "scrape_date": "2025-03-20T01:44:46.305781Z",
      "stabilities": [
        "unstable"
      ],
      "unfree": false,
      "version": "16.8",
      "outputs_to_install": [
        "man",
        "out"
      ],
      "outputs": {
        "dev": "/nix/store/cas6cvbm87xkpbx1clxfn6fs1nglzml1-postgresql-16.8-dev",
        "doc": "/nix/store/aga09pssxz1r8v37m5alzf9xzl391cws-postgresql-16.8-doc",
        "lib": "/nix/store/zdyd5mwc36a3z1g8c5ja7fbhqxrlkyml-postgresql-16.8-lib",
        "man": "/nix/store/3bgf3mx229pgsmw976fvb04j4gma7w3x-postgresql-16.8-man",
        "out": "/nix/store/1qj8dp38pi1zyi7r8lr0dvsk6dr9wvrw-postgresql-16.8"
      },
      "system": "x86_64-darwin",
      "group": "toplevel",
      "priority": 5
    },
    {
      "attr_path": "postgresql_16",
      "broken": false,
      "derivation": "/nix/store/qgs6b0hvsp9gmy6g60lnnfny84q5a0sg-postgresql-16.8.drv",
      "description": "Powerful, open source object-relational database system",
      "install_id": "postgresql_16",
      "license": "PostgreSQL",
      "locked_url": "https://github.com/flox/nixpkgs?rev=b6eaf97c6960d97350c584de1b6dcff03c9daf42",
      "name": "postgresql-16.8",
      "pname": "postgresql_16",
      "rev": "b6eaf97c6960d97350c584de1b6dcff03c9daf42",
      "rev_count": 769969,
      "rev_date": "2025-03-18T09:06:34Z",
      "scrape_date": "2025-03-20T02:04:32.638063Z",
      "stabilities": [
        "unstable"
      ],
      "unfree": false,
      "version": "16.8",
      "outputs_to_install": [
        "man",
        "out"
      ],
      "outputs": {
        "debug": "/nix/store/34bv0r27h9cz9g15rkzmzri5i6jhyq62-postgresql-16.8-debug",
        "dev": "/nix/store/3mgkxjp57c5plvqnh80r2l00z7jjlfb4-postgresql-16.8-dev",
        "doc": "/nix/store/n3zkvn2fps4gf6qami0frj2sjy3lxczj-postgresql-16.8-doc",
        "lib": "/nix/store/vp1fzizqghakbavzs3kwyaizrwzapvc9-postgresql-16.8-lib",
        "man": "/nix/store/g9rz4pnli22i0sp7js1l1g3fm9lf2lp9-postgresql-16.8-man",
        "out": "/nix/store/c8biii3axhckd1fp2sg8lmslbhsx6a6y-postgresql-16.8"
      },
      "system": "x86_64-linux",
      "group": "toplevel",
      "priority": 5
    }
  ]
}
```
