### ISSUE TITLE
pr

### ISSUE THREAD

**Issue by tomberek** [flox/flox#2958]
**Describe the bug:**

**Steps to reproduce:**
1.
```toml
version = 1
[install]
python313.pkg-path = "python313"
pre-commit.pkg-path = "pre-commit"
pre-commit.priority = 8
```
2. `flox activate`
3.
```shell
$ ls -alh $FLOX_ENV/bin/python
lrwxrwxrwx 1 root root 69 Dec 31  1969 /home/tom/flox/office/pre-commit/.flox/run/x86_64-linux.pre-commit.dev/bin/python -> /nix/store/f2krmq3iv5nibcvn4rw7nrnrciqprdkh-python3-3.12.9/bin/python
```

Result:
Shows the pre-commit's python won, despite being given a lower priority.

Expected:
python313 should win

1.3.17-g0005cbc

Notes:

This is due to this line when processing propagated packages
https://github.com/flox/flox/blob/3ec390b22289596ec954541f048b50ca63b3e105/buildenv/builder.pl#L640
> my $priorityCounter = 1000; # don't care about collisions
But this might need to be either `5000` or `originalPriority * 1000` in order for the prioritization to work as expected. Tested that this does solve it, though would need to double check the original intent.

Workaround is to set the priority of python313 to 1 such that it has 1 * 1000 later on:
```toml
version = 1
[install]
python313.pkg-path = "python313"
python313.priority = 1
pre-commit.pkg-path = "pre-commit"
```
