### ISSUE TITLE
init(python): Detect newer Poetry 2.x projects

### ISSUE THREAD

**Issue by dcarley** [flox/flox#3202]
**Acceptance criteria**

The following `pyproject.toml` should be recognised as a Poetry project by `flox init`:
```toml
[project]
name = "quotes_app_python"
version = "0.1.0"
requires-python = ">=3.12"
dependencies = [
    "fastapi (>=0.115.12,<0.116.0)",
    "uvicorn (>=0.34.3,<0.35.0)"
]

[tool.poetry.scripts]
quotes-app-python = "quotes_app_python.main:main"

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
```

**Why**

`poetry init` in 2.x no longer generates `[tool.poetry.dependencies]` by default:

- https://python-poetry.org/docs/dependency-specification/#projectdependencies-and-toolpoetrydependencies

So `flox init` only offers an environment with Python and no Poetry.
