### ISSUE TITLE
build: Python build result won't run (FLOX_ENV_DIRS)

### ISSUE THREAD

**Issue by dcarley** [flox/flox#3312]
**Describe the bug:**

Python build results trigger errors in our standard profile hooks and fail to load dependencies.

Reported for https://github.com/flox/catalog-util since the v1.5 release:

- https://flox-dev.slack.com/archives/C05P6A5J6U8/p1751034632117679

This doesn't fail for https://github.com/flox/flox-manifest-build-examples/tree/main/quotes-app-python because it's using `virtualenv` and bypassing the wrapper script altogether. We should either adjust that example or create a new one that represents this use case.

**Steps to reproduce:**

With the following manifest:
```toml
version = 1

[install]
python3.pkg-path = "python3"

[build.hello-python]
command = """
  mkdir -p $out/bin
  cat >$out/bin/hello-python <<'EOF'
#!/usr/bin/env python3
print("Hello, Python")
EOF
  chmod +x $out/bin/hello-python
"""
```

1. Build: `flox build`
2. Run the result without any existing activations: `env -i ./result-hello-python/bin/hello-python`

Result:
```
/nix/store/pl5acsx8qpcwy7rxlplqwkindpdbrkz2-flox-interpreter-build_executable_wrapper/etc/profile.d/0500_python.sh: line 19: FLOX_ENV_DIRS: unbound variable
```

Presumably related, the build result also has broken dependencies when `FLOX_ENV_DIRS` is populated by another activation:
```
% ./result-catalog-util/bin/catalog-util --help
Traceback (most recent call last):
  File "/nix/store/l7ypwmvm45x4ihp5ysb16y22020iymb1-catalog-util-0.1.0/bin/.catalog-util-wrapped", line 5, in <module>
    import toml
ModuleNotFoundError: No module named 'toml'
```

Expected:
```
Hello, Python
```

**Flox Version (run `flox --version` if possible):**

```
1.5.0-ge9f8e4f
```

**`uname -a` output:**

```
Darwin mba15.local 23.6.0 Darwin Kernel Version 23.6.0: Thu Sep 12 23:36:06 PDT 2024; root:xnu-10063.141.1.701.1~1/RELEASE_ARM64_T8122 arm64 arm Darwin
```
